# Обосновка на проект за Линейна алгебра и аналитична геометрия

Целта на проекта е да се сравнят два метода различни метода за предсказване филмови рейтинги от база данни.

In [97]:
# Стойности за тестване - всяка ненулева стойност в главния диагонал на матрицата R[0][0], R[1][1]... R[20][20]

# Матрична факторизация

In [3]:
import numpy as np
import pandas as pd

import time

from IPython.display import HTML
HTML("<style>.h,.c{display:none}.t{color:#296eaa}.t:active+.h{display:block;}</style>")

import warnings
warnings.filterwarnings("ignore", category=FutureWarning) 

In [4]:
df = pd.read_csv('datasets/user_reviews.csv', index_col=False)
df = df.drop(["User"], axis=1)
matrix = df.to_numpy()

In [7]:
print(matrix)

[[2 4 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 5]
 [4 5 4 4 5 4 5 4 4 4 5 5 3 4 3 3 2 3 3 4 3 4 3]
 [4 4 4 3 5 0 5 0 0 5 2 5 2 5 1 5 5 5 5 4 0 4 0]
 [5 5 4 4 5 4 4 3 4 3 5 5 3 3 5 4 5 5 3 4 3 5 4]
 [4 5 4 4 5 3 5 2 3 2 2 4 3 3 2 3 3 5 4 5 4 4 3]
 [0 4 0 5 5 0 0 0 0 0 0 0 0 0 3 0 5 0 0 5 0 0 0]
 [5 4 4 3 5 4 5 3 5 4 3 4 2 4 3 4 5 0 4 1 2 5 1]
 [0 5 5 4 5 0 0 4 0 0 0 0 3 0 3 4 5 0 5 4 3 0 0]
 [0 4 0 0 0 0 0 1 0 0 0 0 0 0 5 0 5 0 0 2 0 0 0]
 [0 5 5 4 5 0 0 5 3 0 4 0 4 0 5 4 2 0 5 4 2 0 0]
 [0 5 3 4 5 1 0 0 4 5 3 0 0 3 0 5 4 5 4 0 0 0 5]
 [3 4 5 4 5 1 2 2 3 4 2 2 2 2 3 3 5 2 2 2 4 2 0]
 [5 5 0 2 5 0 0 5 0 0 0 0 0 0 1 2 3 3 0 2 0 3 0]
 [0 5 5 5 5 0 0 2 0 0 0 5 3 0 0 0 5 0 0 0 2 0 0]
 [4 5 5 5 5 2 5 2 4 2 2 4 5 5 2 5 4 2 5 5 2 2 2]
 [3 5 5 2 5 4 5 3 4 1 3 3 3 3 3 3 4 4 3 3 3 3 4]
 [0 5 5 2 5 0 5 1 0 5 0 4 3 4 4 4 4 4 0 5 0 4 1]
 [0 4 5 5 5 0 5 3 2 0 2 5 0 0 3 5 0 3 0 5 3 0 3]
 [5 5 5 5 5 5 5 1 3 3 5 5 4 2 5 4 1 0 2 5 1 1 2]
 [5 5 5 5 3 5 5 4 1 1 3 5 5 3 3 4 1 2 3 4 1 4 3]
 [5 4 5 4 5 3 2 4 0 