In [221]:
%run cleanup.ipynb


def cosine_between(vec_a=[], vec_b=[]):
    vec_a = np.array(vec_a)
    vec_b = np.array(vec_b)

    inner = np.inner(vec_a, vec_b)
    norms = LA.norm(vec_a) * LA.norm(vec_b)

    cos = inner / norms
    return cos

def applicable_matrix(matrix_arg, i):
    j = 0
    while j < len(matrix_arg):
        if matrix_arg[j][i] == 0:
            matrix_arg = np.delete(matrix_arg, j, 0)
            j -= 1
        else:
            j += 1

    return matrix_arg

def predict_score(i):
    
    smallest_cosine = 1

    final_matrix = applicable_matrix(matrix, i)
    
    for j in range(len(final_matrix)-1):
        cosine_between_vectors = cosine_between(final_matrix[j], final_matrix[i])

        if smallest_cosine > cosine_between_vectors:
            smallest_cosine = cosine_between_vectors
            similar_user = final_matrix[j]
    print(smallest_cosine)
    print(similar_user)
    print()
    print(similar_user[i])
    

    
start_time = time.time() #start timer

for i in range(13):
    predict_score(i)
exec_time = (time.time() - start_time) #end timer
print(exec_time)

0.31346315310262973
[4 4 4 3 5 0 5 0 0 5 2 5 2 5 1 5 5 5 5 4 0 4 0]

4
0.36055734705059594
[0 4 0 0 0 0 0 1 0 0 0 0 0 0 5 0 5 0 0 2 0 0 0]

4
0.6175475965945012
[0 5 5 5 5 0 0 2 0 0 0 5 3 0 0 0 5 0 0 0 2 0 0]

5
0.5585016120235566
[0 4 0 5 5 0 0 0 0 0 0 0 0 0 3 0 5 0 0 5 0 0 0]

5
0.46565476034098574
[5 5 5 5 3 5 5 4 1 1 3 5 5 3 3 4 1 2 3 4 1 4 3]

3
0.7610526275681431
[0 5 3 4 5 1 0 0 4 5 3 0 0 3 0 5 4 5 4 0 0 0 5]

1
0.7938876565618197
[0 4 5 5 5 0 5 3 2 0 2 5 0 0 3 5 0 3 0 5 3 0 3]

5
0.5006516358818929
[0 4 0 0 0 0 0 1 0 0 0 0 0 0 5 0 5 0 0 2 0 0 0]

1
0.7473285662256068
[0 5 3 4 5 1 0 0 4 5 3 0 0 3 0 5 4 5 4 0 0 0 5]

4
0.37399971964991524
[2 4 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 5]

4
0.6131739163788755
[0 5 3 4 5 1 0 0 4 5 3 0 0 3 0 5 4 5 4 0 0 0 5]

3
0.6118112108014921
[0 5 5 5 5 0 0 2 0 0 0 5 3 0 0 0 5 0 0 0 2 0 0]

5
0.6118112108014921
[0 5 5 5 5 0 0 2 0 0 0 5 3 0 0 0 5 0 0 0 2 0 0]

3
0.030559062957763672
